# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [6]:
# Ejercicio 1

array_1 = np.zeros(12, dtype=int)
print(array_1)


[0 0 0 0 0 0 0 0 0 0 0 0]


In [7]:
# Ejercicio 2

array_2 = np.zeros(10, dtype=int)
array_2[4] = 10
print(array_2)


[ 0  0  0  0 10  0  0  0  0  0]


In [9]:
# Ejercicio 3

array_3 = np.random.randint(10,49, 10)
print(array_3)

[16 24 41 47 16 39 23 37 27 10]


In [20]:
# Ejercicio 4

array_4 = np.random.randint(0,9, (3,3))
print(array_4)


[[8 3 1]
 [3 7 4]
 [5 4 4]]


In [18]:
# Ejercicio 5

array_5 = np.random.rand(100)
print(f"Arreglo aleatorio de longitud 100: {array_5}")

#Media
media = np.mean(array_5)
print(f"La media es: {media}")

#Varianza
varianza = np.var(array_5)
print(f"La varianza es: {varianza}")

Arreglo aleatorio de longitud 100: [8.80833395e-01 6.79960576e-01 9.24798512e-01 9.43178966e-01
 7.02571619e-01 7.44208387e-01 3.84485157e-01 1.93214228e-01
 7.44221739e-01 9.42744869e-01 5.51026085e-01 3.21470959e-01
 3.70409022e-01 6.19899749e-01 5.54990368e-01 9.08880383e-01
 2.31806161e-01 6.71979291e-01 2.97271647e-01 9.06815307e-02
 4.32411374e-01 9.35056200e-02 5.72338988e-01 5.74820488e-01
 3.70787789e-01 3.62805494e-01 6.63029321e-01 5.73670691e-02
 7.12267831e-01 1.48826795e-01 5.97601594e-02 7.68415846e-01
 1.30751553e-01 6.55530001e-01 3.58778949e-01 1.97979158e-01
 2.76200730e-01 3.15553240e-01 5.60619197e-01 3.52417271e-01
 8.26999785e-04 7.06936085e-03 1.72828151e-01 2.38383312e-01
 5.71814523e-01 5.74084979e-02 3.45636376e-02 9.44939620e-01
 9.92645561e-01 2.43338755e-01 3.93277506e-01 8.06880987e-01
 9.44384867e-01 3.93584444e-01 3.11712744e-01 8.96817120e-01
 6.07627744e-01 4.49953356e-01 7.64449479e-01 2.48175088e-01
 2.48609247e-01 8.25958742e-01 4.44023520e-02 5.43

In [24]:
# Ejercicio 6

def calcular_media(array):
    media = np.sum(array)/array.size
    print(f"La media del arreglo es: {media}")

calcular_media(array_5) #caso de uso de la función con el array_5 del ej 5

La media del arreglo es: 0.47583392760423876


In [26]:
# Ejercicio 7

def calcular_varianza(array):
    varianza = np.sum((array - np.mean(array)) ** 2)/array.size
    print(f"La varianza es: {varianza}")

calcular_varianza(array_5)
calcular_varianza(array_4)

La varianza es: 0.08854652089239985
La varianza es: 4.0


In [27]:
# Ejercicio 7 

array_7 = np.random.rand(10)
print(array_7)

[0.33705372 0.80796641 0.4781584  0.79823043 0.72328547 0.57538233
 0.02913272 0.70624978 0.05162072 0.57020088]
